import type { Request, Response } from 'express';
import PDFDocument from 'pdfkit';
import { fail } from '../utils/response';
import * as prescriptionService from '../services/prescriptionService';

export async function createPrescription(req: Request, res: Response) {
  const result = await prescriptionService.createPrescription(req.body);
  if ('error' in result) {
    if (result.error === 'VISIT_NOT_FOUND') return fail(res, 404, 'NOT_FOUND', 'Visit not found');
    return fail(res, 400, 'BAD_REQUEST', 'Unable to create prescription');
  }
  return res.status(201).json(result.prescription);
}

export async function getPrescription(req: Request, res: Response) {
  const { id } = req.params;
  const p = await prescriptionService.getPrescriptionById(id);
  if (!p) return fail(res, 404, 'NOT_FOUND', 'Prescription not found');
  return res.json(p);
}

export async function getPrescriptionPdf(req: Request, res: Response) {
  const { id } = req.params;
  const p = await prescriptionService.getPrescriptionById(id);
  if (!p) return fail(res, 404, 'NOT_FOUND', 'Prescription not found');

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `inline; filename="prescription-${id}.pdf"`);

  const doc = new PDFDocument({ margin: 50 });
  doc.pipe(res);

  doc.fontSize(18).text('Prescription', { align: 'center' });
  doc.moveDown();

  const patient = p.visit.patient;
  const doctor = p.visit.doctor;

  doc.fontSize(12).text(`Patient: ${patient.name} (${patient.patientId})`);
  doc.text(`Age/Gender: ${patient.age} / ${patient.gender}`);
  doc.text(`Doctor: ${doctor.name} (${doctor.specialization})`);
  doc.text(`Visit token: ${p.visit.tokenNumber}`);
  doc.text(`Date: ${p.visit.visitDate.toISOString()}`);
  doc.moveDown();

  if (p.diagnosis) {
    doc.fontSize(12).text(`Diagnosis: ${p.diagnosis}`);
  }
  if (p.clinicalNotes) {
    doc.moveDown(0.5);
    doc.text('Clinical Notes:');
    doc.fontSize(11).text(p.clinicalNotes);
  }

  doc.moveDown();
  doc.fontSize(13).text('Medicines', { underline: true });
  doc.moveDown(0.5);

  p.medicines.forEach((m, idx) => {
    doc.fontSize(11).text(`${idx + 1}. ${m.medicineName}`);
    doc.text(`   Dosage: ${m.dosage} | Frequency: ${m.frequency} | Duration: ${m.duration}`);
    if (m.instructions) doc.text(`   Instructions: ${m.instructions}`);
    doc.moveDown(0.25);
  });

  doc.moveDown();
  doc.fontSize(10).text('Generated by HMS', { align: 'right' });

  doc.end();
}

